// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTransaction(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteTransaction'](arg1, arg2, arg3);
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetMonthSummary(arg1, arg2) {
  return window['go']['main']['App']['GetMonthSummary'](arg1, arg2);
}

export function GetMonthTransactions(arg1, arg2) {
  return window['go']['main']['App']['GetMonthTransactions'](arg1, arg2);
}

export function GetOverallSummary() {
  return window['go']['main']['App']['GetOverallSummary']();
}

export function GetYearSummary(arg1) {
  return window['go']['main']['App']['GetYearSummary'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveTransaction(arg1) {
  return window['go']['main']['App']['SaveTransaction'](arg1);
}
