// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyUpdate(arg1:main.UpdateInfo):Promise<void>;

export function CheckForUpdate():Promise<main.UpdateInfo>;

export function DeleteTransaction(arg1:string,arg2:number,arg3:number):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetDataDir():Promise<string>;

export function GetMonthSummary(arg1:number,arg2:number):Promise<main.MonthSummary>;

export function GetMonthTransactions(arg1:number,arg2:number):Promise<main.MonthTransactions>;

export function GetOverallSummary():Promise<main.OverallSummary>;

export function GetYearSummary(arg1:number):Promise<main.YearSummary>;

export function Greet(arg1:string):Promise<string>;

export function RestartApp():Promise<void>;

export function SaveTransaction(arg1:main.Transaction):Promise<main.Transaction>;
